project_id = "wvllorttpekoxksrtiwo"

[functions.generate-sermon]
verify_jwt = false

[functions.generate-devotional]
verify_jwt = false

[functions.generate-bible-commentary]
verify_jwt = false

[functions.generate-slides]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false
