// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-saved-content.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/list-saved-content.ts
var list_saved_content_default = defineTool({
  name: "list_saved_content",
  title: "Listar conte\xFAdos salvos",
  description: "Lista os conte\xFAdos salvos pelo pregador (prega\xE7\xF5es, devocionais, estudos, verbetes do dicion\xE1rio). Filtre por tipo com content_type.",
  inputSchema: {
    content_type: z.string().optional().describe("Filtro opcional de tipo: pregacao, devocional, estudo, dicionario, questionario."),
    limit: z.number().optional().describe("N\xFAmero m\xE1ximo de itens (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ content_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("saved_content").select("id, title, content_type, content, created_at").order("created_at", { ascending: false }).limit(max);
    if (content_type) query = query.eq("content_type", content_type);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/save-content.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var save_content_default = defineTool2({
  name: "save_content",
  title: "Salvar conte\xFAdo",
  description: "Salva um conte\xFAdo (prega\xE7\xE3o, devocional, estudo, verbete) na \xC1rea do Pregador do usu\xE1rio autenticado.",
  inputSchema: {
    title: z2.string().describe("T\xEDtulo do conte\xFAdo."),
    content: z2.string().describe("Texto completo do conte\xFAdo, em markdown."),
    content_type: z2.string().optional().describe("Tipo: pregacao, devocional, estudo, dicionario, questionario. Padr\xE3o: pregacao.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, content_type }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("saved_content").insert({
      user_id: ctx.getUserId(),
      title,
      content,
      content_type: content_type ?? "pregacao"
    }).select("id, title, content_type, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-notes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_notes_default = defineTool3({
  name: "list_notes",
  title: "Listar notas pessoais",
  description: "Lista as notas pessoais do usu\xE1rio autenticado, opcionalmente filtradas por categoria.",
  inputSchema: {
    category: z3.string().optional().describe("Categoria da nota (opcional)."),
    limit: z3.number().optional().describe("N\xFAmero m\xE1ximo de notas (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("personal_notes").select("id, title, content, category, bible_reference, updated_at").order("updated_at", { ascending: false }).limit(max);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/create-note.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_note_default = defineTool4({
  name: "create_note",
  title: "Criar nota pessoal",
  description: "Cria uma nota pessoal de estudo para o usu\xE1rio autenticado.",
  inputSchema: {
    title: z4.string().describe("T\xEDtulo da nota."),
    content: z4.string().describe("Conte\xFAdo da nota."),
    category: z4.string().optional().describe("Categoria da nota (opcional)."),
    bible_reference: z4.string().optional().describe("Refer\xEAncia b\xEDblica relacionada, ex.: Jo\xE3o 3:16.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, category, bible_reference }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const insert = {
      user_id: ctx.getUserId(),
      title,
      content,
      bible_reference: bible_reference ?? null
    };
    if (category) insert.category = category;
    const { data, error } = await supabaseForUser(ctx).from("personal_notes").insert(insert).select("id, title, category, bible_reference, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/get-daily-devotional.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_daily_devotional_default = defineTool5({
  name: "get_daily_devotional",
  title: "Devocional do dia",
  description: "Retorna o devocional di\xE1rio publicado no app (vers\xEDculo, reflex\xE3o e ora\xE7\xE3o). Use a data no formato AAAA-MM-DD para dias anteriores.",
  inputSchema: {
    date: z5.string().optional().describe("Data no formato AAAA-MM-DD. Padr\xE3o: o devocional mais recente.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("devocional_diario").select("*").order("created_at", { ascending: false }).limit(1);
    if (date) query = query.eq("data", date);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    if (!data?.length) return errorResult("Nenhum devocional encontrado para essa data.");
    return jsonResult(data[0]);
  }
});

// src/lib/mcp/index.ts
var projectRef = "wvllorttpekoxksrtiwo";
var mcp_default = defineMcp({
  name: "pregador-celestial",
  title: "Pregador Celestial",
  version: "0.1.0",
  instructions: "Ferramentas do Pregador Celestial. Permitem ler e salvar conte\xFAdos da \xC1rea do Pregador (prega\xE7\xF5es, devocionais, estudos, verbetes), gerenciar notas pessoais de estudo b\xEDblico e consultar o devocional di\xE1rio. Todas as opera\xE7\xF5es s\xE3o feitas na conta do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_saved_content_default, save_content_default, list_notes_default, create_note_default, get_daily_devotional_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
